docs: Add hint how to install vscode
eclipse-ankaios/ankaios pull request #186
Opened 2024-02-08 15:06 UTC by simone-weiss

Only a small change, but one can not assume that people
    use vscode already.

# Definition of Done

The PR shall be merged only if all items mentioned in [CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md#how-to-contribute) have been followed. In case an item is not applicable as described, please provide a short explanation in the description.

- [ ] All steps in [CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md#how-to-contribute) have been handled

2024-02-08 15:06 UTC, simone-weiss commented
- Note also the svgs are not displayed good if one uses a dark github setting and checks from the markdown files.

2024-02-08 16:13 UTC, windsource approved these changes
LGTM 👍

2024-02-08 16:16 UTC, windsource requested changes
Only small change required

2024-02-08 16:16 UTC, windsource commented on doc/docs/development/build.md
> +- Vscode ([Installation instructions](https://code.visualstudio.com/download))
```suggestion
- Visual Studio Code ([Installation instructions](https://code.visualstudio.com/download))
```

2024-02-08 17:14 UTC, simone-weiss commented on doc/docs/development/build.md
> +- Vscode ([Installation instructions](https://code.visualstudio.com/download))
Good point - done

2024-02-09 08:00 UTC, windsource commented
> * Note also the svgs are not displayed good if one uses a dark github setting and checks from the markdown files.

Thanks for the hint. I have created a #187 for that.

2024-02-09 08:59 UTC, windsource approved these changes
OK

2024-02-09 09:00 UTC, merged