Splitting proto file into 3 distinct files
eclipse-ankaios/ankaios pull request #259
Opened 2024-04-26 08:32 UTC by krucod3

Issues: #172

# Definition of Done

The PR shall be merged only if all items mentioned in [CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md#how-to-contribute) have been followed. In case an item is not applicable as described, please provide a short explanation in the description.

- [ ] All steps in [CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md#how-to-contribute) have been handled

2024-04-30 13:50 UTC, krucod3 commented
From technical point of view - all done.
What is left to do is taking care of the tracing.

2024-05-08 08:44 UTC, krucod3 commented
All done now. I also added new requirements for the API lib. Review can be done, but
❗ DON'T MERGE BEFORE v0.3.1 IS ON MAIN ❗ 
We have breaking changes here that must only be released with v0.4.

2024-05-08 13:56 UTC, lingnoi requested changes
for the first 37 files, more will follow ...

2024-05-10 11:53 UTC, lingnoi reviewed
no more findings

2024-05-17 08:22 UTC, krucod3 commented on grpc/proto/grpc_api.proto
> +}
I explicitly did not move it as it is only an internal message sent by Ankaios. The user cannot send it and never sees it.

2024-05-17 08:26 UTC, krucod3 commented on doc/docs/usage/upgrading/v0_3_to_v0_4.md
> +Ankaios is designed for an interchangeable communication middleware between the server, the agents and the CLI. The currently available, and thus default, implementation is done with gRPC. In oder to
Well it sounds better, but:
* adaptable does not mean interchangeable 
* when we say "segregating" we should name both parts or say segregating the gRPC from the Control Interface.

I'll think about a better formulation and add a proposal.

2024-05-17 11:52 UTC, krucod3 commented on common/src/to_server_interface.rs
> +// Copyright (c) 2023 Elektrobit Automotive GmbHc
I wonder how did this happen...

2024-05-17 11:55 UTC, krucod3 commented on api/doc/drawio/unit_overview.drawio.svg
You are absolutely right 👍 
Thx!

2024-05-17 13:36 UTC, krucod3 commented on doc/docs/usage/upgrading/v0_3_to_v0_4.md
> +Ankaios is designed for an interchangeable communication middleware between the server, the agents and the CLI. The currently available, and thus default, implementation is done with gRPC. In oder to
```suggestion
Ankaios is designed for an interchangeable communication middleware between the server, the agents and the CLI. The currently available, and thus default, implementation is done with gRPC. In oder to make it more clear which messages belong to the fixed Control Interface and which to the interchangeable gRPC middleware, we have carved out the gRPC API into a separate file named `grpc_api.proto`.



Ankaios facilitates server-agent-CLI communication through an interchangeable middleware, currently implemented using gRPC. By segregating the gRPC API into a distinct `grpc_api.proto` file, we clearly show the target and purpose of this interface.
```

2024-05-17 13:38 UTC, krucod3 commented
All done or answered.

2024-06-11 09:22 UTC, lingnoi approved these changes
LGTM 👍

2024-06-11 15:00 UTC, inf17101 commented
I reviewed commit https://github.com/eclipse-ankaios/ankaios/pull/259/commits/2a545a7afeb27a42274e85697020aaea2667112b.

LGTM 👍

2024-06-12 09:11 UTC, merged